### ISSUE TITLE
Unable to mock static inline functions

### ISSUE THREAD

**Issue by jverce** [meekrosoft/fff#7]
Hi there,
I am trying to mock a couple of functions from the linux/i2c-dev.h header, which declaration is as follows:

static inline __s32 i2c_smbus_write_word_data(int file, __u8 command, __u16 value) { ... }
static inline __s32 i2c_smbus_write_word_data(int file, __u8 command, __u8 value) { ... }

Unfortunately, FFF doesn't seem to be taking my mocks as valid mocks for these functions calls. I am not getting de return sequence according to what I've set. I'm always getting the same value (which I assume it's because the real functions are being called instead of the mock ones).

My mock declarations are the following:
FAKE_VALUE_FUNC( __s32, i2c_smbus_write_word_data, int, __u8, __u16);
FAKE_VALUE_FUNC( __s32, i2c_smbus_write_byte_data, int, __u8, __u8);

Does it have something to do with the way the functions are declared?

Thank you!
Regards,

**Comment by acazzaniga** [comment]
Hi there, 
I know this has been discussed long time ago. We are facing the same issue described here, but since it is related to static inline function in vendor code's header we would like to know whether it is possible to put in place a solution similar to what has been done for Cmock (https://github.com/ThrowTheSwitch/CMock/pull/261).

Thanks a lot.
Best regards,
Andrea
